version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs-app
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/testdb
    command: sh -c "npx prisma db push && npx ts-node prisma/seed.ts && npm run start"

volumes:
  pgdata:
